### ISSUE TITLE
Add code for publishing relevant data on OEP

### ISSUE THREAD

**Issue by gplssm** [openego/eGon-data#200]
### Tasks

- [ ] Add function that updates metadata fields of all datasets to be published on the OEP
  - [ ] Update/overwrite `publicationDate` with date of publication on OEP
  - [ ] Add URL OEP table as URI in field `id`
  - [ ] Insert URL of `id` also in `resources` > `schema` > `fields` > `path`

**Comment by nesnoj** [comment]
Closed in favour of #451
