### ISSUE TITLE
Use 100.000 household demand profiles instead of 10.000

### ISSUE THREAD

**Issue by gplssm** [openego/eGon-data#294]
With #256 household electricity demand profiles got integrated into egon-data. At this step, 10.000 profiles where used in total. Replace the 10.000 profiles by 100.000 which we got from IEE.

### Tasks

- [ ] Merge 3 `.h5` files
- [ ] Test if code works well with 100.000 profiles
- [ ] Upload to existing Zenodo deposit with heat demand profiles
- [ ] Add metadata according to mail discussion

cf. mail on 17.6.21
