### ISSUE TITLE
Create CH4 buses im neighbouring countries (eGon2035)

### ISSUE THREAD

**Issue by AmeliaNadal** [openego/eGon-data#545]
Currently, the the gas pipes connected to neighbouring countries are defined as links, but these have one bus which is not defined (the one abroad). This should be fixed.

**TODOs**

- [ ] Define one CH4 bus per neighbouring country. See https://github.com/openego/eGon-data/blob/features/%23138-integrate-pysa-eur-sec/src/egon/data/datasets/electrical_neighbours.py 
- [ ] Redefine the links modelling the cross border gas pipes.
- [ ] Optional (to be done later): Redefine the capacities of the cross border gas pipes with https://entsog.eu/sites/default/files/2021-07/ENTSOG_TYNDP_2020_Annex_C2_Capacities_per_country.xlsx
