### ISSUE TITLE
Zenodo data bundle v0.6

### ISSUE THREAD

**Issue by nesnoj** [openego/eGon-data#627]
Update of [data bundle](https://zenodo.org/record/5743452).

To be added (tick if added on NC):
- [x] UPDATED eMobility trip data #553 @nesnoj
- [x] p-e-s data
- [ ] ~MaStR data (new data and drop the sandbox dependency) #519 @nesnoj~
- [ ] ~updated p-e-s output dataset (depends on #604 ) @ulfmueller~

Feel free to add further datasets..

**Comment by nesnoj** [comment]
@IlkaCu Could you please create the new version? (updated eMobility trip data only)
The old `.tar.gz` file can be deleted, you can find 2 new files on the server, cf. [readme on NC](https://next.rl-institut.de/f/1286631).

**Comment by IlkaCu** [comment]
The new data bundle version 0.6 is available here: https://zenodo.org/record/6520140

**Comment by nesnoj** [comment]
> The new data bundle version 0.6 is available here: https://zenodo.org/record/6520140

Thank you! The deposit id needs to be updated in the `datasets.yml` - are you planning to do this as well?

**Comment by IlkaCu** [comment]
I can do that as well.

**Comment by IlkaCu** [comment]
I update the deposit id on this feature branch: https://github.com/openego/eGon-data/tree/features/%23627-zenodo-v0.6
Please add additional changes, if needed.

**Comment by nesnoj** [comment]
> I update the deposit id on this feature branch: https://github.com/openego/eGon-data/tree/features/%23627-zenodo-v0.6 Please add additional changes, if needed.

Thx, I'll create a PR
