### ISSUE TITLE
Transfer zensus_vg250 scripts

### ISSUE THREAD

**Issue by IlkaCu** [openego/eGon-data#7]
Scripts related to preprocessing section zensus_vg250 need to be reviewed, adjusted and transfered to the new egon-data repo.

**Tasks**

- [x] Add data filtering for zensus with population > 0 and inside Germany
- [x] Add metadata for the resulting table of above, see [here](https://github.com/openego/data_processing/blob/5edca414212ccb4b1df6b046bf916bc2ebb7b4c6/preprocessing/zensus_vg250/ego_pp_destatis_zensus_metadata.sql)
- [x] Calculate population per municipality. Use the [open_ego data processing script](https://github.com/openego/data_processing/blob/5edca414212ccb4b1df6b046bf916bc2ebb7b4c6/preprocessing/vg250/ego_dp_structure_boundaries_vg250.sql#L450-L687). There might be a duplication with the first task
- [x] Add note to CHANGELOG

**Comment by gplssm** [comment]
While I transferred vg250 import scripts, I've realized the is as well code that depends on the existence of census data. Since that is not the case right now, I move the remaining parts to here. So, in addition to the actual "zensus_vg250 scripts", integrate the following code as well:

https://github.com/openego/data_processing/blob/5edca414212ccb4b1df6b046bf916bc2ebb7b4c6/preprocessing/vg250/ego_dp_structure_boundaries_vg250.sql#L450-L687

Don't forget to update the table about required materialized views of vg250: https://github.com/openego/eGon-data/issues/68#issue-757060493

**Comment by gplssm** [comment]
While working on this, I've realized that VG250 has partially invalid geometry

`SELECT bez, gen, ST_IsValid(geometry) FROM boundaries.vg250_sta;`

"Bundesrepublik"	"Deutschland"	false
"Bundesrepublik"	"Deutschland"	true
"Bundesrepublik"	"Deutschland"	true
"Bundesrepublik"	"Deutschland"	true
"Bundesrepublik"	"Deutschland"	true
"Bundesrepublik"	"Deutschland"	true
"Bundesrepublik"	"Deutschland"	true
"Bundesrepublik"	"Deutschland"	true
"--"	"Österreich (Bodensee)"	true
"--"	"Schweiz (Bodensee)"	true
"Bundesrepublik"	"Deutschland (Bodensee)"	true

I don't know if it's relevant, but at least the documentation of [ST_Contains](https://postgis.net/docs/ST_Contains.html) (which I'm using on this data) says that invalid geometry might return unexpected results.
