### ISSUE TITLE
Switch to GitHub actions for CI

### ISSUE THREAD

**Issue by gplssm** [openego/eGon-data#92]
We decided in #63 to switch to GitHub actions for our CI jobs.

This [blog entry](https://mg.pov.lt/blog/switching-to-github-actions.html) gives some hints for configuring GH actions using tox. Take the [build.yml](https://github.com/mgedmin/project-summary/blob/master/.github/workflows/build.yml) and [tox.ini](https://github.com/mgedmin/project-summary/blob/master/tox.ini) as example configuration.

Further reading

- https://hynek.me/articles/python-github-actions/
- https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-python#running-tests-with-tox
- https://pakstech.com/blog/gentle-introduction-github-actions/

### Tasks

First, we only setup the jobs to run on linux and do the general configuration

- [x] Add minimal `build.yml` using tox and running code tests
- [x] Activate (uncomment) other environments and include them in gh-actions mapping in `tox.ini`

We take care about running all tests an Windows platform as well

[tox GH actions docs](https://pypi.org/project/tox-gh-actions/) explain how to specify different platform as matrix.

- [ ] ~Make CI jobs run on Windows~ #96

We take care about running all tests an macOS platform as well

- [ ] ~Make CI jobs run on macOS~ #106 

Finalizing

- [x] Add badge in README
- [x] Update docs: replace Travis with GitHub actions
- [x] Add to CHANGELOG

### Open questions

- How to show code coverage report to the user? For example in a PR I would like to know how my contributions affect the overall coverage?
- Does it make sense to separate different kind of checks into different jobs? By doing so not everything is in one big bunch of tests and checks. In addition it would be easier to trace errors. I we decide to do, we do it in a separate issue.
- What about duplicate tests/checks? One example: docs/RTD

**Comment by gplssm** [comment]
Test on windows won't be included here, maybe elsewhere https://github.com/openego/eGon-data/issues/96

**Comment by gplssm** [comment]
macos fails with Python 3.7 and 3.8. Have a look in the old `travis.yml` which macos specific things got installed there. If not successful, move it to another issue.

**Comment by gplssm** [comment]
> macos fails with Python 3.7 and 3.8. Have a look in the old `travis.yml` which macos specific things got installed there. If not successful, move it to another issue.

Decided to not further dig into that rabbit hole. I deactivate python versions, where tests are failing and moved the task to #106
